// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'E:/SubAPI-frontend/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import RedditOutlined from 'E:/SubAPI-frontend/node_modules/@ant-design/icons/es/icons/RedditOutlined';
import CrownOutlined from 'E:/SubAPI-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import ApiOutlined from 'E:/SubAPI-frontend/node_modules/@ant-design/icons/es/icons/ApiOutlined';
import TeamOutlined from 'E:/SubAPI-frontend/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import UserOutlined from 'E:/SubAPI-frontend/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, RedditOutlined, CrownOutlined, ApiOutlined, TeamOutlined, UserOutlined };
